"use client";
import { useAppDispatch, useAppSelector } from '@/store';
import { decrement, increment, initCountState } from '@/store/counter/counterSlice';
import { useEffect } from 'react';
interface Props {
    value?: number
}

// Generated by https://quicktype.io

export interface CounterResponse {
    count: number;
}



const getApiCounter = async () => {
    const res = await fetch('/api/counter');
    const data = await res.json();
    return data as CounterResponse;

}

export const CartCounter = ({ value = 0}:Props) => {
    const count = useAppSelector(state => state.counter.count);
    const dispatch = useAppDispatch();

    /* useEffect(()=>{
        dispatch(initCountState(value));
    },[]) */

    useEffect(() => {
        getApiCounter().then(({count}) => {
            dispatch(initCountState(count));
        })
    }, [])

    return (
        <>
            <span className="text-9xl">{count}</span>
            <div className="flex">
                <button
                    onClick={() => dispatch(increment())}
                    className="flex items-center justify-center p-2 bg-gray-800 text-white hover:bg-gray-400 transition-all w-[100px] mr-2 rounded-xl" >
                    + 1
                </button>
                <button
                    onClick={() => dispatch(decrement())}
                    className="flex items-center justify-center p-2 bg-gray-800 text-white hover:bg-gray-400 transition-all w-[100px] mr-2 rounded-xl" >
                    - 1
                </button>
            </div>
        </>
    )
}
